from django.urls import path
from . import views
from .views import (
    VacationListView,
    VacationDetailView,
    apply_for_vacation,
    add_to_favorites,
    CandidateDetailView,
    ResumeListView,
    ResumeDetailView,
    ResumeCreateView,
    ResumeDeleteView,
    ResumeUpdateView,
    remove_from_favorites,
    CategoryListView,
    CategoryDetailView,
    index,
    search,
)

app_name = "job_hunter"

urlpatterns = [
    path("", index, name="index"),
    path("search/", search, name="search"),
    path("categories/", CategoryListView.as_view(), name="categories"),
    path("categories/<int:pk>/",
         CategoryDetailView.as_view(),
         name="category_detail"),
    path("vacancies/",
         VacationListView.as_view(),
         name="vacancies-list"),
    path("vacancies/<int:pk>/",
         VacationDetailView.as_view(),
         name="vacancies-detail"),
    path("vacancies/<int:pk>/apply/",
         apply_for_vacation,
         name="apply-for-vacation"),
    path("vacancies/<int:pk>/favorite/",
         add_to_favorites,
         name="add-to-favorites"),
    path(
        "vacancies/<int:pk>/remove_favorite/",
        remove_from_favorites,
        name="remove-from-favorites",
    ),
    path("candidates/<int:pk>/",
         CandidateDetailView.as_view(),
         name="candidates-detail"),
    path("resumes/",
         ResumeListView.as_view(),
         name="resume-list"),
    path("resumes/<int:pk>/",
         ResumeDetailView.as_view(),
         name="resume-detail"),
    path("resumes/create/",
         ResumeCreateView.as_view(),
         name="resume-create"),
    path("resumes/<int:pk>/delete/",
         ResumeDeleteView.as_view(),
         name="resume-delete"),
    path("resumes/<int:pk>/update/",
         ResumeUpdateView.as_view(),
         name="resume-update"),
]
