# Generated by Django 5.0.6 on 2024-05-18 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='job_hunter.vacation'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='vacations', to=settings.AUTH_USER_MODEL),
        ),
    ]
