# Generated by Django 5.0.6 on 2024-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0002_candidate_favorites_alter_vacation_candidates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(choices=[('no_experience', 'No experience'), ('1_year', '1 year'), ('3_years', '3 years'), ('5_years', '5 years')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='experience',
            field=models.CharField(choices=[('no_experience', 'No experience'), ('1_year', '1 year'), ('3_years', '3 years'), ('5_years', '5 years')], max_length=20),
        ),
    ]
