# Generated by Django 5.0.6 on 2024-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0003_alter_candidate_options_alter_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='type_work',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], default='remote', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='type_work_time',
            field=models.CharField(choices=[('part_time', 'Part time'), ('full_time', 'Full time')], default='Remote', max_length=20),
            preserve_default=False,
        ),
    ]
