# Generated by Django 5.0.6 on 2024-05-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hunter', '0004_vacation_type_work_vacation_type_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='location',
            field=models.CharField(default='Kyiv', max_length=255),
            preserve_default=False,
        ),
    ]
