# Generated by Django 5.0.6 on 2024-05-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0005_vacation_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="resume",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="vacation",
            options={"ordering": ["created_at"]},
        ),
    ]
