# Generated by Django 5.0.6 on 2024-05-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0006_alter_category_options_alter_resume_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="resumes",
        ),
        migrations.AddField(
            model_name="candidate",
            name="resumes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="job_hunter.resume",
            ),
        ),
    ]
