# Generated by Django 5.0.6 on 2024-05-20 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_hunter", "0007_remove_candidate_resumes_candidate_resumes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="resumes",
        ),
        migrations.AddField(
            model_name="resume",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
